# Generated by Django 6.0.2 on 2026-04-08 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='similarity_threshold',
            field=models.FloatField(default=0.8, help_text='Maximum allowed similarity score for new documents in this batch', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
