# Generated by Django 6.0.2 on 2026-04-10 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_batch_similarity_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='similarity_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Highest similarity score compared to existing documents in the batch', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', help_text='Whether the document was accepted or rejected based on threshold', max_length=10),
        ),
    ]
